sudo: required
services:
  - docker

before_install:
  - docker build -t moatef1/docker-react -f Dockerfile.dev .
   
script:
  - docker run moatef1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "northeast-2"  
  app: docker-react
  env: " DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-808277092346"
  bucket_path: "docker"
  on:
    bransh: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    

